name: app_resto_manager
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  image_picker: ^1.2.1
  fl_chart: ^1.2.0
  intl: ^0.20.2
  pdf: ^3.12.0
  printing: ^5.14.3
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1 # Aligné correctement ici

# Cette section doit être tout à fait à gauche
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_akwaba.png"
  adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  # N'oublie pas de déclarer ton dossier assets ici aussi !
  assets:
    - assets/images/logo_akwaba.png